# Generated by Django 4.2 on 2023-06-19 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("S", "Strenght"),
                            ("A", "Agility"),
                            ("I", "Intelligence"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "team",
                    models.CharField(
                        choices=[("SEN", "Sentinel"), ("SCO", "Scourge")], max_length=10
                    ),
                ),
                ("component_killer", models.FloatField()),
                ("component_assistant", models.FloatField()),
                ("component_teamplayer", models.FloatField()),
                ("icon", models.ImageField(blank=True, upload_to="icons/")),
                ("art", models.ImageField(blank=True, upload_to="arts/")),
                ("games", models.IntegerField(blank=True, null=True)),
                ("wins_percent", models.FloatField(blank=True, null=True)),
                ("kills", models.IntegerField(blank=True, null=True)),
                ("deaths", models.IntegerField(blank=True, null=True)),
                ("assists", models.IntegerField(blank=True, null=True)),
                ("leader_index", models.FloatField(blank=True, null=True)),
                ("killer_index", models.FloatField(blank=True, null=True)),
                ("assistant_index", models.FloatField(blank=True, null=True)),
                ("percentile_killer", models.FloatField(blank=True, null=True)),
                ("percentile_assistant", models.FloatField(blank=True, null=True)),
                ("rate", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-rate", "-wins_percent"],
            },
        ),
        migrations.CreateModel(
            name="Appearance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kills", models.PositiveSmallIntegerField()),
                ("deaths", models.PositiveSmallIntegerField()),
                ("assists", models.PositiveSmallIntegerField()),
                ("game", models.IntegerField(blank=True, null=True)),
                ("leader_index", models.FloatField(blank=True, null=True)),
                ("winner", models.BooleanField()),
                (
                    "hero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="heroes.hero"
                    ),
                ),
            ],
        ),
    ]
